#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
IPSEC FRITZER

a tool for generating a mac os x and ios native ipsec client compatible vpn config
by Martin Brüggemann <martin@brgmn.de>

Copyright (c) 2010 Martin Brüggemann

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
"""

TEMPLATE = """/*
 * AVM FRITZBOX VPN CONFIG ({filename})
 * generated by IPSEC FRITZER v0.1
 *
{account_list}
*/

vpncfg {{
    connections {account_configurations}
    ike_forward_rules = "udp 0.0.0.0:500 0.0.0.0:500",
                        "udp 0.0.0.0:4500 0.0.0.0:4500";
}}
// EOF
"""

accountTemplate = """ {{
            name = "{accountName}@{domain}";
            enabled = yes;
            conn_type = conntype_user;
            remoteip = 0.0.0.0;
            remote_virtualip = {localNetwork}.{localIP};
            phase2remoteid {{
                ipaddr = {localNetwork}.{localIP};
            }}
            remoteid {{
                    key_id = "{accountName}@{domain}";
            }}
            accesslist = "permit ip any {ACCESSLIST_IP} 255.255.255.255";
            key = "{secret}";
            always_renew = no;
            reject_not_encrypted = no;
            dont_filter_netbios = yes;
            localip = 0.0.0.0;
            local_virtualip = 0.0.0.0;
            mode = phase1_mode_aggressive;
            phase1ss = "all/all/all";
            keytype = connkeytype_pre_shared;
            cert_do_server_auth = no;
            use_nat_t = yes;
            use_xauth = yes;
            use_cfgmode = no;
            xauth {{
                valid=yes;
                username="{accountName}";
                passwd="{password}";
            }}
            phase2ss = "esp-all-all/ah-none/comp-all/no-pfs";
            phase2localid {{
                ipnet {{
                    ipaddr = 0.0.0.0;
                    mask = 0.0.0.0;
                }}
            }}
    }}
"""

import datetime
from config import localNetwork, domain, accounts, routeAllTrafficTroughVPN

print(
    "############################################################################\n"
    "# IPSEC FRITZER v0.1 by Martin Brüggemann <blog@brgmn.de>                  #\n"
    "# Python version by Daniel Rech <dr@nwebs.de>                              #\n"
    "# http://github.com/brgmn/ipsecfritzer                                     #\n"
    "############################################################################\n"
)

filename = 'vpn_config_{0}.txt'.format(datetime.datetime.now().strftime('%Y-%m-%d-%H:%M'))

output = TEMPLATE.format(
    filename=filename,
    account_list = '\n'.join([
        ' * {0} | {1} | {2}\n'.format(accountName, accountData['secret'], accountData['password'])
        for accountName, accountData in accounts.items()
    ]),
    account_configurations='\n'.join([
        accountTemplate.format(
            accountName=accountName,
            domain=domain,
            localNetwork=localNetwork,
            ACCESSLIST_IP='{0}.{1}'.format(
                localNetwork,
                accountData['localIP'] if routeAllTrafficTroughVPN else 0
            ),
            **accountData
        )
        for accountName, accountData in accounts.items()
    ])
)

with open(filename, 'wb') as fp:
    fp.write(output)

print('FritzBox!-VPN-Config succesfully written to {0}'.format(filename))
